version: "3"

volumes:
  db:
  redis:
  node_modules:

services:
  app:
    container_name: task-manager
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run start:debug
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres_task-manager
    image: postgres:13.2-alpine
    volumes:
      - db:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

  redis:
    container_name: task-manager_redis
    image: redis:6.2.0-alpine
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"
